---
jobs:
  fast_finish: true
  include:
    - stage: linting
      script: find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck:v0.7.0 "$line"; done;
language: shell
services:
  - docker
stages:
  - linting
