---
env:
  - SHELLCHECK_VERSION="v0.4.7"
  - HADOLINT_VERSION="v1.2.6"
jobs:
  include:
    - stage: linting
      script: find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck:"$SHELLCHECK_VERSION" "$line"; done
    - script: find . -type f -iname "Dockerfile" | while read -r line; do; echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm -w="/mnt" hadolint/hadolint:"$HADOLINT_VERSION" hadolint --ignore DL3013 --ignore DL3016 --ignore SC1090 "$line"; done;
language: shell
matrix:
  fast_finish: true
services:
  - docker
stages:
  - linting
sudo: required
