apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-config
  namespace: kube-system
data:
  traefik.toml: |
    logLevel = "INFO"
    [api]
    [kubernetes]
    [metrics]
      [metrics.prometheus]
