---
- hosts: all
  gather_facts: yes
  post_tasks:
    - name: Copy the Kubernetes cluster initialization script
      copy:
        dest: /tmp/bootstrap-kubernetes-{{kubernetes_classifier}}.sh
        mode: 0777
        remote_src: yes
        src: /vagrant/scripts/linux/bootstrap-kubernetes-{{kubernetes_classifier}}.sh
    - name: Copy the Kubelet configuration script
      copy:
        dest: /tmp/kubelet-configuration.sh
        mode: 0777
        remote_src: yes
        src: /vagrant/scripts/linux/kubelet-configuration.sh
    - name: Copy the GlusterFS initialization script
      copy:
        dest: /tmp/bootstrap-glusterfs.sh
        mode: 0777
        remote_src: yes
        src: /vagrant/scripts/linux/bootstrap-glusterfs.sh
    - name: Copy the monitoring stack initialization script
      copy:
        dest: /tmp/bootstrap-monitoring.sh
        mode: 0777
        remote_src: yes
        src: /vagrant/scripts/linux/bootstrap-monitoring.sh
    - name: Configure Kubelet
      become: yes
      shell: "/tmp/kubelet-configuration.sh {{broadcast_address}}"
    - name: Initialize Kubernetes cluster
      become: yes
      shell: "/tmp/bootstrap-kubernetes-{{kubernetes_classifier}}.sh {{kubernetes_master_1_ip}} {{kubeadm_token}}"
    - name: Initialize GlusterFS
      become: yes
      shell: "/tmp/bootstrap-glusterfs.sh"
      when: inventory_hostname == "kubernetes-master-1"
    - name: Initialize the monitoring stack
      become: yes
      shell: "/tmp/bootstrap-monitoring.sh"
      when: inventory_hostname == "kubernetes-master-1"
  roles:
    - role: ferrarimarco.kubernetes
      become: yes
      ferrarimarco_kubernetes_filesystem: glusterfs
    - role: andrewrothstein.kubernetes-helm
      become: yes
