replicas: 2

persistence:
  enabled: true
  size: 0.5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "glusterfs-storage"

adminUser: admin
adminPassword: strongpassword

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server.prometheus.svc.cluster.local
     access: proxy
     isDefault: true

service:
  type: NodePort
